name: {name of workflow}
on:
  push:
    branches: -main
  pull_request:
    branches: -main

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: python:3.9-slim

    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: |
        python -m pip install --upgrade pip : 
        pip install -r requirements.txt :

         -name: Lint with flake8
           run :|
           flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics 
           flake8 service --count --max-complexity=10 --max-line-length=127 --statistics 

           -name:Run unit test with nose
            run:nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
            ---   
apiVersion: tekton.dev/v1betal
kind: Task
metadata:
  name: cleanup
spec:
  description: This task will clean up a workspace by deleting all the files.
  workspaces:
    - name: source
  steps:
    - name: remove
      image: alpine:3
      env:
        - name: WORKSPACE_SOURCE_PATH
          value: $(workspace.source.path)
      workingDir: {placeholder}
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      script: |
        
        #!/usr/bin/bash/env sh
        set -eu

