name: {name of workflow}
on:
  push:
    branches: -main
  pull_request:
    branches: -main

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: python:3.9-slim

    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: |
        python -m pip install --upgrade pip : 
        pip install -r requirements.txt :

         -name: Lint with flake8
           run :|
           flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics 
           flake8 service --count --max-complexity=10 --max-line-length=127 --statistics 

           -name: Run unit test with nose 
            run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
     ---
apiVersion: {placeholder}
kind: {placeholder}
metadata:
  name: {placeholder}
spec:
  description: This task will clean up a workspace by deleting all the files.
  workspaces:
    - name: {placeholder}
  steps:
    - name: {placeholder}
      image: {placeholder}
      env:
        - name: {placeholder}
          value: {placeholder}
      workingDir: {placeholder}
      securityContext:
        runAsNonRoot: {placeholder}
        runAsUser: {placeholder}
      script: |
        {placeholder}

          #!/bin/bash
  set -e
  python -m pip install --upgrade pip wheel
  pip install -r requirements.txt
  nosetests $(params.args)
